import { readFile, writeFile } from "node:fs/promises";
import process from "node:process";
import { resolve } from "node:path";
import { URL, fileURLToPath, pathToFileURL } from "node:url";

const defaultPackagePath = fileURLToPath(
  new URL("../package.json", import.meta.url),
);
const defaultOutputPath = fileURLToPath(
  new URL("../src/generated/version.ts", import.meta.url),
);

export function renderVersionModule(version) {
  if (
    typeof version !== "string" ||
    !/^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?$/.test(version)
  )
    throw new Error(`Invalid package version ${JSON.stringify(version)}.`);
  return `// Generated from packages/core/package.json by scripts/generate-version.mjs.\n// Do not edit this file directly.\nexport const PACKAGE_VERSION = ${JSON.stringify(version)} as const;\n`;
}

export async function generateVersion({
  check = false,
  packagePath = defaultPackagePath,
  outputPath = defaultOutputPath,
} = {}) {
  const packageJson = JSON.parse(await readFile(packagePath, "utf8"));
  const expected = renderVersionModule(packageJson.version);
  if (check) {
    const current = await readFile(outputPath, "utf8").catch(() => "");
    if (current !== expected)
      throw new Error(
        "Generated package version is stale. Run pnpm --filter @brip/glyphscramble generate:version.",
      );
    return;
  }
  await writeFile(outputPath, expected);
}

function option(name) {
  const index = process.argv.indexOf(name);
  if (index < 0) return undefined;
  const value = process.argv[index + 1];
  if (!value || value.startsWith("--"))
    throw new Error(`${name} requires a path.`);
  return resolve(value);
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href)
  await generateVersion({
    check: process.argv.includes("--check"),
    packagePath: option("--package") ?? defaultPackagePath,
    outputPath: option("--output") ?? defaultOutputPath,
  });
